//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dnevnik.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DnevnikDataBaseEntities : DbContext
    {
        public DnevnikDataBaseEntities()
            : base("name=DnevnikDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClassUsers> ClassUsers { get; set; }
        public virtual DbSet<Ochenka> Ochenka { get; set; }
        public virtual DbSet<OchenkaAndUser> OchenkaAndUser { get; set; }
        public virtual DbSet<Predmet> Predmet { get; set; }
        public virtual DbSet<PredmetAndUser> PredmetAndUser { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
